### ISSUE TITLE
Wrong version of ember-cli-app-version in 1.13.12 addon package.json

### ISSUE THREAD

**Issue by kenips** [twokul/ember-cli-release-notes#1]
https://github.com/twokul/ember-cli-release-notes/blob/0ecafc92599ac2c0ff300318cab17efa3465da97/1.13.9/addon/package.json#L23 should be `^1.0.0`?

**Comment by twokul** [comment]
https://github.com/twokul/ember-cli-release-notes/commit/10b37d37a4c2935c199199f74ebd27ae61f44d32
